name: I teach 109
description: I'm Luke, I teach CMPT-109 at Montclair State University and this is my blog.

#baseurl: /~maciakl/blog
baseurl:
url: http://msuweb.montclair.edu/~maciakl/blog

# Enable pagination
gems: ["jekyll-paginate"] # only needed on Jekyll 3, comment out otherwise
paginate: 5

category_dir: /
exclude: ["README.markdown", "component.json", "grunt.js", "package.json", "node_modules", "Rakefile"]

permalink: pretty

markdown: kramdown
