name: I teach 109
description: I'm Luke, I teach CMPT-109 at Montclair State University and this is my blog.

baseurl: /~maciakl/blog
url: http://msuweb.montclair.edu/~maciakl/blog

category_dir: /
exclude: ["README.markdown", "component.json", "grunt.js", "package.json", "node_modules", "Rakefile"]

permalink: pretty

markdown: kramdown
